### ISSUE TITLE
Fragments?

### ISSUE THREAD

**Issue by borjaruiz** [Gnod/ParallaxListView#6]
Is it possible to use it with fragments?

**Comment by Gnod** [comment]
It seem that there is a problem in working with Fragments, as currently implement rely on onWindowFocusChanged to do some calculation. I will fixed it soon. Currently, if you want to use it with fragments, you can try think  of some way to call setViewsBounds in Activity's onWindowFocusChanged or after all view's layout state or modified the ParallaxListView's setViewsBounds and give a directly value to  mImageViewHeight.

**Comment by borjaruiz** [comment]
I've used EventBus to change fragment's mListView from the Activity. My problem is that I have a drawerLayout, and in the first time, this works, but when I click a menu option to open a new fragment, it doesn't work.

**Comment by Gnod** [comment]
@borjaruiz In that case, can you send me a demo project of your using?  to [gnodsy#gmail.com]

**Comment by Gnod** [comment]
@borjaruiz It might be that in you situation, the setViewBounds method was called only once(as it is invoke in onWindowFocusChanged, open new fragment might not get setViewBounds invoked), I has commit a new implement, you can have a try.

**Comment by borjaruiz** [comment]
@Gnod I finally used another library. Thanks.
